
jobs:
  include:
    - os: linux
      language: java
      dist: trusty
      sudo: true
      jdk: openjdk11
    - os: windows
      language: shell

env:
  - MAVEN_VERSION=3.6.3

before_install:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    choco install openjdk11 --version 11.0.5.10;
    export JAVA_HOME='/c/Program Files/OpenJDK/openjdk-11.0.5_10'
    export PATH="${PATH}:${JAVA_HOME}/bin";
    choco install maven --version ${MAVEN_VERSION};
    export PATH="${PATH}:/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin";
  fi;
 - "echo $PATH"
 - "export JAVA_OPTS=-Xmx512m"
 - "mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=${MAVEN_VERSION}"

# Default installation command is 
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# this is what we test as our build phase so skip it here.
install:
 - true

before_script:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
     sudo service mysql stop;
     sudo service postgresql stop;
     sudo service acpid stop;
     sudo service atd stop;
     sudo service cron stop;
     sudo service memcached stop;
     sudo service ntp stop;
     sudo service rabbitmq-server stop;
     sudo service resolvconf stop;
     sudo service sshguard stop;
     sudo service ssh stop;
   fi
    
script:
 - ./mvnw -Dfcrepo.streaming.parallel=true install -B -V

notifications:
  irc: "irc.freenode.org#fcrepo"
  email:
      - fedora-tech@googlegroups.com

